In [5]:
import numpy as np
import pandas as pd

In [6]:
df=pd.read_csv('BlackFriday.csv')

In [7]:
df.head()

User_ID Product_ID Gender   Age  Occupation City_Category  \
0  1000001  P00069042      F  0-17          10             A   
1  1000001  P00248942      F  0-17          10             A   
2  1000001  P00087842      F  0-17          10             A   
3  1000001  P00085442      F  0-17          10             A   
4  1000002  P00285442      M   55+          16             C   

  Stay_In_Current_City_Years  Marital_Status  Product_Category_1  \
0                          2               0                   3   
1                          2               0                   1   
2                          2               0                  12   
3                          2               0                  12   
4                         4+               0                   8   

   Product_Category_2  Product_Category_3  Purchase  
0                 NaN                 NaN      8370  
1                 6.0                14.0     15200  
2                 NaN                 NaN      1422  
3                14.0                 NaN      1057  
4                 NaN                 NaN      7969

In [8]:
df.describe()

User_ID    Occupation  Marital_Status  Product_Category_1  \
count  5.375770e+05  537577.00000   537577.000000       537577.000000   
mean   1.002992e+06       8.08271        0.408797            5.295546   
std    1.714393e+03       6.52412        0.491612            3.750701   
min    1.000001e+06       0.00000        0.000000            1.000000   
25%    1.001495e+06       2.00000        0.000000            1.000000   
50%    1.003031e+06       7.00000        0.000000            5.000000   
75%    1.004417e+06      14.00000        1.000000            8.000000   
max    1.006040e+06      20.00000        1.000000           18.000000   

       Product_Category_2  Product_Category_3       Purchase  
count       370591.000000       164278.000000  537577.000000  
mean             9.842144           12.669840    9333.859853  
std              5.087259            4.124341    4981.022133  
min              2.000000            3.000000     185.000000  
25%              5.000000            9.000000    5866.000000  
50%              9.000000           14.000000    8062.000000  
75%             15.000000           16.000000   12073.000000  
max             18.000000           18.000000   23961.000000

In [9]:
del df['User_ID']

In [10]:
del df['Product_ID']

In [11]:
df.isnull().sum()

Gender                             0
Age                                0
Occupation                         0
City_Category                      0
Stay_In_Current_City_Years         0
Marital_Status                     0
Product_Category_1                 0
Product_Category_2            166986
Product_Category_3            373299
Purchase                           0
dtype: int64

In [12]:
def getnum(g):
    if(g=="M"):
        return 1
    else:
        return 0

df['Gender']=df['Gender'].apply(getnum)

In [13]:
len(df)

537577

In [14]:
del df['Product_Category_2']
del df['Product_Category_3']

In [68]:
import seaborn as sns

In [15]:
set(df['Gender'])

{0, 1}

In [16]:
# set(df['Age'])

In [17]:
# set(df['Occupation'])

In [18]:
# set(df['City_Category'])

In [19]:
def getnum(c):
    if(c=="A"):
        return 1
    elif(c=="B"):
        return 2
    else:
        return 3

df['City_Category']=df['City_Category'].apply(getnum)

In [20]:
# set(df['Stay_In_Current_City_Years'])

In [21]:
set(df['Marital_Status'])

{0, 1}

In [22]:
df.head()

Gender   Age  Occupation  City_Category Stay_In_Current_City_Years  \
0       0  0-17          10              1                          2   
1       0  0-17          10              1                          2   
2       0  0-17          10              1                          2   
3       0  0-17          10              1                          2   
4       1   55+          16              3                         4+   

   Marital_Status  Product_Category_1  Purchase  
0               0                   3      8370  
1               0                   1     15200  
2               0                  12      1422  
3               0                  12      1057  
4               0                   8      7969

In [23]:
def getnum(c):
    if(c=='4+'):
        return 5

df['Stay_In_Current_City_Years']=df['Stay_In_Current_City_Years'].apply(getnum)

In [24]:
def getnum(s):
    if(s=='55+'):
        return 55
    else:
        l=s.split('-')
        return (int(l[0])+int(l[1]))/2
df['Age']=df['Age'].apply(getnum)

In [25]:
df.head()

Gender   Age  Occupation  City_Category  Stay_In_Current_City_Years  \
0       0   8.5          10              1                         NaN   
1       0   8.5          10              1                         NaN   
2       0   8.5          10              1                         NaN   
3       0   8.5          10              1                         NaN   
4       1  55.0          16              3                         5.0   

   Marital_Status  Product_Category_1  Purchase  
0               0                   3      8370  
1               0                   1     15200  
2               0                  12      1422  
3               0                  12      1057  
4               0                   8      7969

In [26]:
# set(df['Stay_In_Current_City_Years'])

In [27]:
df.isnull().sum()

Gender                             0
Age                                0
Occupation                         0
City_Category                      0
Stay_In_Current_City_Years    454688
Marital_Status                     0
Product_Category_1                 0
Purchase                           0
dtype: int64

In [28]:
len(df)

537577

In [29]:
del df['Stay_In_Current_City_Years']

In [30]:
df.head()

Gender   Age  Occupation  City_Category  Marital_Status  \
0       0   8.5          10              1               0   
1       0   8.5          10              1               0   
2       0   8.5          10              1               0   
3       0   8.5          10              1               0   
4       1  55.0          16              3               0   

   Product_Category_1  Purchase  
0                   3      8370  
1                   1     15200  
2                  12      1422  
3                  12      1057  
4                   8      7969

In [31]:
x=df.iloc[:,:6].values

In [32]:
x[0]

array([ 0. ,  8.5, 10. ,  1. ,  0. ,  3. ])

In [33]:
y=df['Purchase'].values

In [34]:
y

array([ 8370, 15200,  1422, ...,  8043,  7172,  6875], dtype=int64)

In [35]:
from sklearn.model_selection import train_test_split

In [36]:
x_train,x_test,y_train,y_test=train_test_split(x,y)

In [37]:
from sklearn.linear_model import LinearRegression

In [38]:
clf=LinearRegression()

In [39]:
clf.fit(x,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [40]:
 clf.score(x_test,y_test)

0.10562395436581196

In [41]:
from sklearn.linear_model import ElasticNet

In [52]:
clf=ElasticNet(alpha=0.000001)

In [53]:
clf.fit(x_train,y_train)

ElasticNet(alpha=1e-06, copy_X=True, fit_intercept=True, l1_ratio=0.5,
      max_iter=1000, normalize=False, positive=False, precompute=False,
      random_state=None, selection='cyclic', tol=0.0001, warm_start=False)

In [54]:
 clf.score(x_test,y_test)

0.10561370785234235

In [55]:
from sklearn.linear_model import Ridge

In [65]:
clf=Ridge(alpha=0.00001)

In [66]:
clf.fit(x_train,y_train)

Ridge(alpha=1e-05, copy_X=True, fit_intercept=True, max_iter=None,
   normalize=False, random_state=None, solver='auto', tol=0.001)

In [67]:
clf.score(x_test,y_test)

0.10561370772851597

In [51]:
t=pd.read_csv('test.csv')

In [52]:
t

User_ID Product_ID Gender    Age  Occupation City_Category  \
0       1000004  P00128942      M  46-50           7             B   
1       1000009  P00113442      M  26-35          17             C   
2       1000010  P00288442      F  36-45           1             B   
3       1000010  P00145342      F  36-45           1             B   
4       1000011  P00053842      F  26-35           1             C   
5       1000013  P00350442      M  46-50           1             C   
6       1000013  P00155442      M  46-50           1             C   
7       1000013   P0094542      M  46-50           1             C   
8       1000015  P00161842      M  26-35           7             A   
9       1000022  P00067942      M  18-25          15             A   
10      1000026  P00046742      M  26-35           7             B   
11      1000026  P00040042      M  26-35           7             B   
12      1000026  P00196542      M  26-35           7             B   
13      1000026  P00004542      M  26-35           7             B   
14      1000028  P00159542      F  26-35           1             C   
15      1000029  P00111542      M  36-45           7             C   
16      1000033  P00121042      M  46-50           3             A   
17      1000033  P00344442      M  46-50           3             A   
18      1000034  P00265242      F  18-25           0             A   
19      1000035   P0096642      M  46-50           1             C   
20      1000036  P00303042      M  26-35           3             B   
21      1000036  P00059642      M  26-35           3             B   
22      1000042  P00030842      M  26-35           8             C   
23      1000045  P00346442      F  46-50          16             A   
24      1000045  P00357242      F  46-50          16             A   
25      1000045  P00284742      F  46-50          16             A   
26      1000048  P00110842      M  26-35           4             B   
27      1000048  P00251642      M  26-35           4             B   
28      1000053  P00136742      M  26-35           0             B   
29      1000053   P0097342      M  26-35           0             B   
...         ...        ...    ...    ...         ...           ...   
233569  1005996  P00184242      F  26-35           0             B   
233570  1005996  P00045342      F  26-35           0             B   
233571  1006001  P00124642      F  26-35           7             A   
233572  1006002  P00121142      M  51-55           0             C   
233573  1006002  P00233542      M  51-55           0             C   
233574  1006002  P00226342      M  51-55           0             C   
233575  1006002  P00284842      M  51-55           0             C   
233576  1006003  P00313342      F  46-50          17             C   
233577  1006010  P00223542      M  36-45           0             C   
233578  1006013  P00020342      F  26-35          20             C   
233579  1006016  P00014842      M  46-50           1             B   
233580  1006016  P00109542      M  46-50           1             B   
233581  1006018  P00071442      M  36-45           1             C   
233582  1006021  P00112542      M  26-35          12             B   
233583  1006021  P00003442      M  26-35          12             B   
233584  1006023  P00262242      M  26-35           0             C   
233585  1006025  P00161142      F  26-35           1             B   
233586  1006026  P00110742      M  36-45           6             C   
233587  1006028  P00162442      M  18-25           4             A   
233588  1006030  P00129842      M  26-35          17             C   
233589  1006030  P00241442      M  26-35          17             C   
233590  1006032  P00252442      M  46-50           7             A   
233591  1006033  P00127642      M  51-55          13             B   
233592  1006035  P00135742      F  26-35           1             C   
233593  1006036  P00255442      F  26-35          15             B   
233594  1006036  P

In [53]:
def getnum(g):
    if(g=="M"):
        return 1
    else:
        return 0

t['Gender']=t['Gender'].apply(getnum)

In [54]:
def getnum(c):
    if(c=="A"):
        return 1
    elif(c=="B"):
        return 2
    else:
        return 3

t['City_Category']=t['City_Category'].apply(getnum)

In [55]:
def getnum(c):
    if(c=='4+'):
        return 5

t['Stay_In_Current_City_Years']=t['Stay_In_Current_City_Years'].apply(getnum)

In [56]:
def getnum(s):
    if(s=='55+'):
        return 55
    else:
        l=s.split('-')
        return (int(l[0])+int(l[1]))/2
t['Age']=t['Age'].apply(getnum)

In [57]:
t.head()

User_ID Product_ID  Gender   Age  Occupation  City_Category  \
0  1000004  P00128942       1  48.0           7              2   
1  1000009  P00113442       1  30.5          17              3   
2  1000010  P00288442       0  40.5           1              2   
3  1000010  P00145342       0  40.5           1              2   
4  1000011  P00053842       0  30.5           1              3   

   Stay_In_Current_City_Years  Marital_Status  Product_Category_1  \
0                         NaN               1                   1   
1                         NaN               0                   3   
2                         5.0               1                   5   
3                         5.0               1                   4   
4                         NaN               0                   4   

   Product_Category_2  Product_Category_3  
0                11.0                 NaN  
1                 5.0                 NaN  
2                14.0                 NaN  
3                 9.0                 NaN  
4                 5.0                12.0

In [58]:
t.isnull().sum()

User_ID                            0
Product_ID                         0
Gender                             0
Age                                0
Occupation                         0
City_Category                      0
Stay_In_Current_City_Years    197654
Marital_Status                     0
Product_Category_1                 0
Product_Category_2             72344
Product_Category_3            162562
dtype: int64

In [59]:
del t['Stay_In_Current_City_Years']

In [60]:
del t['Product_Category_2']
del t['Product_Category_3']

In [61]:
t.head()

User_ID Product_ID  Gender   Age  Occupation  City_Category  \
0  1000004  P00128942       1  48.0           7              2   
1  1000009  P00113442       1  30.5          17              3   
2  1000010  P00288442       0  40.5           1              2   
3  1000010  P00145342       0  40.5           1              2   
4  1000011  P00053842       0  30.5           1              3   

   Marital_Status  Product_Category_1  
0               1                   1  
1               0                   3  
2               1                   5  
3               1                   4  
4               0                   4

In [71]:
xt=t.iloc[:,2:].values

In [72]:
xt[0]

array([ 1., 48.,  7.,  2.,  1.,  1.])

In [73]:
xt.shape,x_train.shape

((233599, 6), (403182, 6))

In [79]:
ypred=clf.predict(xt)

In [81]:
uid=t['User_ID'].values

In [82]:
pid=t['Product_ID'].values

In [83]:
uid.shape,pid.shape,len(ypred)

((233599,), (233599,), 233599)

In [87]:
s=np.c_[uid,pid,ypred]

In [88]:
s[0]

array([1000004, 'P00128942', 11391.190185440639], dtype=object)

In [98]:
np.savetxt('black.csv',s,header="User_ID,Product_ID,Purchase",delimiter=',',fmt="%s,%s,%s")